services:
  app:
    build: .
    depends_on:
      - db
    ports:
      - 8000:8000

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo_api
  
  adminer:
    image: adminer
    ports:
      - 8080:8080